package constant

const (
	SERVER_HOST = "localhost"
	SERVER_PORT = "3000"
	SERVER_TYPE = "tcp"
	CLIENT_HOST = "localhost"
)

const (
	DATE_TIME_FORMAT = "15:04:05 02-01-2006"
)

const (
	INFO  = "INFO"
	ERROR = "ERROR"
)

const (
	SERVER_BANNER = "IF9fICAgIF9fICAgICBfXyAgX18gICAgICAgIF9fX19fXyAgIF9fX19fXyAgIF9fX19fXyAgDQovXCAiLS4vICBcICAgL1wgXF9cIFwgICAgICAvXCAgX19fXCAvXF9fICBfXCAvXCAgPT0gXCANClwgXCBcLS4vXCBcICBcIFxfX19fIFwgICAgIFwgXCAgX19cIFwvXy9cIFwvIFwgXCAgXy0vIA0KIFwgXF9cIFwgXF9cICBcL1xfX19fX1wgICAgIFwgXF9cICAgICAgXCBcX1wgIFwgXF9cICAgDQogIFwvXy8gIFwvXy8gICBcL19fX19fLyAgICAgIFwvXy8gICAgICAgXC9fLyAgIFwvXy8gICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KQnkgQXJ0dXJv"
	CLIENT_BANNER = "IF9fX19fXyAgICAgX18gICAgICAgICBfXyAgICAgX19fX19fICAgICBfXyAgIF9fICAgICBfX19fX18gIA0KL1wgIF9fX1wgICAvXCBcICAgICAgIC9cIFwgICAvXCAgX19fXCAgIC9cICItLlwgXCAgIC9cX18gIF9cIA0KXCBcIFxfX19fICBcIFwgXF9fX18gIFwgXCBcICBcIFwgIF9fXCAgIFwgXCBcLS4gIFwgIFwvXy9cIFwvIA0KIFwgXF9fX19fXCAgXCBcX19fX19cICBcIFxfXCAgXCBcX19fX19cICBcIFxfXFwiXF9cICAgIFwgXF9cIA0KICBcL19fX19fLyAgIFwvX19fX18vICAgXC9fLyAgIFwvX19fX18vICAgXC9fLyBcL18vICAgICBcL18vIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KQnkgQXJ0dXJv"
)

const (
	RECEIVE_MODE = "receive"
	SEND_MODE    = "send"
)

const (
	CONFIG_PATH = "/resource/topics.json"
)

const (
	SEPARATOR = "\\"
)

const (
	HEADER_TITLE string = "HEADER  "
	BODY_TITLE          = "BODY  "
	REQ_SEP             = "\n"
)

const (
	REGISTER_CLIENT   = "REGISTER_CLIENT"
	SEND_FILE         = "SEND_FILE"
	UNREGISTER_CLIENT = "UNREGISTER_CLIENT"
)

const (
	MAX_SIZE_MESSAGE = 2000000
)

const (
	TEST_FILES_DIRECTORY = "./resource/files"
)
