package constant

const (
	SERVER_HOST = "localhost"
	SERVER_PORT = "8000"
	SERVER_TYPE = "tcp"
)

const (
	DATE_TIME_FORMAT = "16:01:05 26-09-2022"
)

const (
	INFO  = "INFO"
	ERROR = "ERROR"
)

const (
	BANNER = "IF9fICAgIF9fICAgICBfXyAgX18gICAgICAgIF9fX19fXyAgIF9fX19fXyAgIF9fX19fXyAgDQovXCAiLS4vICBcICAgL1wgXF9cIFwgICAgICAvXCAgX19fXCAvXF9fICBfXCAvXCAgPT0gXCANClwgXCBcLS4vXCBcICBcIFxfX19fIFwgICAgIFwgXCAgX19cIFwvXy9cIFwvIFwgXCAgXy0vIA0KIFwgXF9cIFwgXF9cICBcL1xfX19fX1wgICAgIFwgXF9cICAgICAgXCBcX1wgIFwgXF9cICAgDQogIFwvXy8gIFwvXy8gICBcL19fX19fLyAgICAgIFwvXy8gICAgICAgXC9fLyAgIFwvXy8gICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KQnkgQXJ0dXJv"
)
